# Generated by Django 5.0.7 on 2024-07-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reservation_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="reservation_time",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="guests",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
